### ISSUE TITLE
[Suggestion] Config for multiple seekers?

### ISSUE THREAD

**Issue by ZigzagAwaka** [gogozooom/Hide-and-Seek-LC-#1]
Hello, thanks for making this mod !
I'm using it since the last update (yeah, pretty recent lmao) but I think it could be nice to add a config to set the number of seekers in one game (set to a chosen number, or having it random) when there is a lot of players in the game

But honnestly, the best would be a zombie mod, when a hidder is killed, he got resurected as a seeker so the more time passes the more seekers ! (with this, seekers should be immune to other seekers guns lmao otherwise it could lead to chaos)

Anyway, have a great day:)

**Comment by gogozooom** [comment]
I agree, the next update is planned to be a more major one, and it is likely to add what you mentioned and _**more**_.

Here is a section of the TODO.txt file describing planned features.

> Hiders escape back to ship
> 	DESC: And the hiders having to escape back to the ship is a good idea,
> 	I could make it so that after a certain point the exits will be unlocked and the hiders will be notified that they can escape.
> 	And I also need to make it so that the players are invincible once they are in the ship so it can act like a safe zone.
> 	(And now that I'm thinking about it, disable flipping the lever to leave early to give the other hiders a chance,
> 	AND also make the ship automatically leave once all the hiders that are still alive are in the ship.)
> 
> Give purpose to caught hiders.

_**On adding more seekers,**_ I'd have to do quite the reworking to get this working. Practically every corner of my mod assumes that there will only ever be one seeker, which makes things difficult, to say the least. No worries though, this rework should be simpler compared to many other reworks I have done in the past.

_**For the config property,**_ it will allow you to either set a specific amount of seekers (1-3... etc.) or a percentage (1%-99%).
If you set it to an integer, it is quite self-explanatory, (That many seekers will be chosen every round)
But if you set it to a percentage, it will multiply that by the current number of players to get the number of seekers to pick each round. (Example, 10 players, 20% value, 10*20% or 10*0.2 = 2. The number of seekers chosen will be 2. The number will also be rounded in cases of 1.4 -> 1, and 1.5 -> 2)
Along with this, you will be able to configure **how** the extra seekers are chosen.
For example, you could have "Seeker Choose Behavior" set to "Lever" which will make the seeker whoever the lever puller is.
Then you could set the new property "Extra Seeker Choose Behavior" to "Ship" making whoever stays in the ship the extra seekers.

Then there would need to be another config property called "Force Min Seekers" which, if true, will guarantee the specified number of seekers even if no one is in the ship for example.

And of course, there are a lot of edge cases that, although interesting, will take quite the time to explain. I don't even know if you're following along or not this far yet XD.

As for when to expect the update. Uhh, I don't normally enjoy making promises, (with the fear of not fulfilling them) but, let's just say: "_**by the end of this month. (Oct 31)**_" Just to keep me motivated.

For some context, I am an early college student, who still lives in his mom's house, is soon to get a job, and also does swim team regularly. All of that said, I am a very busy human being. However, I still get a good amount of free time every now and then. I just gotta remember to work on this project instead of the many other ones I have lying around. So... Yeah.

Thank you for your understanding and interest in my mod, big update coming your way!

**Comment by ZigzagAwaka** [comment]
Oh boy thanks for the response, i did not expect something that big lmao
I totally understand you are not 100% free to work on this, but don't worry, im a LC modder myself and I also don't work on mods everyday so yeah no problem for that

Im happy to hear that you are planing to increase the number of seekers tho ! But any chance for a zombie seekers mod like i described in my original post?
I just think having hidders turning into seekers on death could be insane (and better than just increasing the number of seekers)
for example, if a hidder dies, he will stay 60secs (configurable) in spectate mod and then be resurected as a seeeker
Of course if you don't like the idea, it's fine, having the number of seekers increased manually is also a good option !

Thanks

**Comment by gogozooom** [comment]
I was already planning on a zombie-like feature actually. I just forgot to elaborate on it more in my last reply.

(In the TODO.txt file)
> Give purpose to caught hiders.

After I implement extra seekers, adding this next should be a breeze.
I could also add a config file for the **_"zombie's"_** items. So people can choose if they want the seeker to have a Shovel, Knife, or even a Shotgun idk.

The thing that will occupy the most time in adding this are the edge cases. Like **_what happens when a zombie player dies again?_** **Do they respawn?** _Or just die permanently?_ Do I make it a config file? (That's probably what I'll end up doing XD)
And what happens when **the round is just ending** and **someone revives as a zombie**? Will it _break_ anything?
You get the point.

And speaking of the round ending, I might change how players are rewarded at the end of the round. I think giving the hiders who survived more money compared to the hiders who died earlier in the round would be better. I could add an algorithm to give hiders more money depending on how long they survived. And for the seekers (More applicable when multiple seekers are added) the percentage of total hiders they caught will affect their total reward. And of course, this all changes when zombies are enabled. I could probably still give zombie players their hider reward despite them working against the hider at that moment, but I could also give them an additional reward for every player they kill, slightly like the seekers.

So lots to consider! **This will certainly be a major update.**

_(Me just realizing how many instances of lethal company I'm gonna need to run...)_
_(Hopfully my 32 gb of ram and 4060 covers this...)_
_(I'll also probably need to disable the modded interiors, they take up a lot of resources...)_

**Comment by ZigzagAwaka** [comment]
Yeah take your time with that don't worry !

**Comment by gogozooom** [comment]
The [latest pre-release](https://github.com/gogozooom/Hide-and-Seek-LC-/releases/tag/V1.4.0.2) is out, zombies exist now!

**Comment by ZigzagAwaka** [comment]
Thanks for this ! I will test the nightly release this week !
