### ISSUE TITLE
[Suggestion] Feedback on the critical injury ability + Input utils compatibility

### ISSUE THREAD

**Issue by ZigzagAwaka** [gogozooom/Hide-and-Seek-LC-#2]
Hello, it's me again for another suggestion lmao !

Concerning the critical injury ability, i think it's way too powerful because hidders just have to activate it and... that's it the seeker can be one shot with a shovel. It could be nice to allow the seeker to auto regen itself or modifying this ability completly, too broken imo

Also other thing, right now the mod can't be played well with a controller since you need to press keyboard keys and use the moose to select abilities, you should add compatibility with LethalCompany_InputUtils to allow players to rebind their controls and allows controller players to play ... well, with a controller ahah

**Comment by gogozooom** [comment]
**(Added to the TODO list!)**

I've also had the same thought. The critical injury ability has become much more powerful with the addition of the shovel and other items as spawnable abilities. However, I would like to keep this ability **_to an extent_** because I enjoy the strategizing it allows.

The most obvious nerf is to make it cost more and have a longer cooldown.
On top of that, I'll add 3-second warning before the target player's health goes critical. That way the seeker will know to be cautious in case the hiders are trying to pull a _"wombo-combo"_ on them.

Even with all these nerfs, the wombo-combo is still possible, but harder for the hiders to pull off, and easier for the seeker to avoid, resulting in a desirable balance.

**Comment by ZigzagAwaka** [comment]
I agree, but at the same time it's not really funny for the seeker to be comboed, just my opinion of course
Also, same thing for the hidders pov, the teleportation to a random place ability is also really op, less cost than invisibility or swap and no downsides (swap will 80% kill the other player, and invisibility is still risky you have to be smart)

Honnestly you know what
Can you add a specific config file separate from the original config (so like HideAndSeek.Abilities.cfg) where the players could choose to activate or deactivate every abilities in the mod, as well as setting all abilities price ?
I know it's a lot to ask, but i would really like to disable critical injury and teleportation

By playing for a long time, i also noticed than the bracken can't kill people ? That's a little sad. I kinda want to lower the price a little bit now. This is why im asking for a huge config file to personalize everything

**Comment by gogozooom** [comment]
Ok, I can add a ability config file.
And on the teleport and swap ability, I've already nerfed that this update. It now has a startup delay of 3 seconds _(with special animations and sounds like the ship inverse teleporter ✨)_ So now there is much more opportunity for the other side to react. In fact, would you like a nightly build so you can test out abilities and such before a full release? Considering you're the only person other than my friends that puts this much interest in my mod XD

The Update is in a pretty stable state right now, I could submit a build to GitHub once I get home.

**Comment by ZigzagAwaka** [comment]
Thanks for that, the teleportation animation is a really good addition!
It's not that i don't want to use the last update right away, but it's kinda complicated to explain every player in the lobby to download an external .dll and replace it in the mod's files (+ some can have anti virus that prevents manual dll download)
This means that i will probably not test this build before the official release but thanks anyway !

Ahah if i have a lot of interest in this mod it's because it's so fun ! Thats all lmao

Im personnaly waiting for the ability config file to close this issue btw

**Comment by gogozooom** [comment]
Oh right, maybe I could upload a separate nightly build to the thuderstore to make installing the mod easier... I'll do that sometime today.

**Comment by ZigzagAwaka** [comment]
As you wish ! I will definitily use the nightly version if you do that

**Comment by gogozooom** [comment]
The Nightly build has been uploaded!
https://thunderstore.io/c/lethal-company/p/Gogozooom/Hide_And_Seek_Nightly/

Took me all night to get the ability config to work, (pun intended) Json utility wasn't working so I had to resort to my own formatting methods. And figuring out how to sync with the host was an interesting challenge...

Tell me how it goes!

**Comment by ZigzagAwaka** [comment]
Oh thanks ! Unfortunatly, me and my friends are only playing in the week end so i will not be able to test that before friday
But thanks for your hard work, this is something that i really appreciate, keep up the good work !

**Comment by gogozooom** [comment]
I found a clever way to nerf the critical injury ability! Now not only can you only use it every two minutes instead of one, but the target can avoid it! (Play yourself to find out how! I think it's cool enough not to get spoiled)

**Comment by ZigzagAwaka** [comment]
Oh interesting, i will definitily look into it this week then
Now... there is only input utils rebind controls that remains... before this mod goes from insane to perfect lmao

**Comment by ZigzagAwaka** [comment]
Ah also another report but this was already there in the stable build, so the nightly also has it
When you become seeker and you were previsouly a hidder, open the ability menu and hidder abilities will be displayed, you have to select the favorite tab and then go back to all to finally have the seekers abilities displayed
This is the same when you were a seeker and after this day you are a hidder
Small issue yeah but just the let you know

**Comment by gogozooom** [comment]
Added to my to-do list!

For the multiple seeker config, I'm probably going to make it _floor_ the value instead of _round_ it.

This is what it would look like if I _rounded_ the input: (x represents the number of players, y is the number of seekers)
![image](https://github.com/user-attachments/assets/ae86f1a4-a7d0-4dce-b101-db2c82013a22)

And this is what it would look like if I _floored_ the input:
![image](https://github.com/user-attachments/assets/a27ed052-1a0b-4a3c-9e6e-d069523abb05)

Overall, flooring the value makes much more sense and is more predictable. However, I'm not sure if this will entirely fix the problem with balancing. So I might look into the longer day mod and _take inspiration_.

As for all the issues you mentioned, I will look into those and try to recreate as many of them as I can.
I already have an idea on how to fix the spectating UI, I kinda had to do some weird workaround to make the spectating UI disappear, because otherwise, you would have the UI enabled when you respawn as a zombie so... I think the UI is handled with an animator, which makes it a little difficult to just, _disable it_, it seems like it has to go through all the round ended UI before it fully gets properly disabled. But I digress.

Certain abilities being incorrectly displayed should be an easy fix. The problem with the critical injury ability, I'm not so sure... It might be hard to even recreate the issue because I test my mod with multiple LAN instances on the same computer, which gives the game the most ideal network situation. Because of that, if there were an issue related to a player having a slightly worse connection, it could cause unpredictable issues to occur. With that being said though, I doubt this is actually a network issue. I will try many combinations with 3 players, two seekers, and the host being both seeker one round, and hider the other. If I'm not able to recreate it, then I will probably just assume it was a fluke? Until I run into it myself, there is probably a random error happening in the log that I could trace down if it happens to me.

After I work with this handful of issues, all I should need to do is add a tutorial for anyone who has never played my Hide and Seek mod before _(It will show up for new people who just got the mod but they can quickly close it if they already know what they're doing)_ and finally the 1.4.0 update will be out!

I'm actually surprised with how quickly I was able to add some of these seemingly complicated features and behaviors to the mod, all I really did was be consistent with when I worked on it, which helps I guess.
I'm exited to see what my friends think when I show them all the new features I have added!

**Comment by ZigzagAwaka** [comment]
Yeah i agree, you did an incredible job, thanks for that !

Floored values should be better, true. Ahah take inspiration ok i see where you are going, the mod is there if you want to see it https://thunderstore.io/c/lethal-company/p/Megalophobia/Longer_Day/ it's a simple time speed scale mod

Well, for the critical injury i actually have no idea if this is real or not. i just verified footage in my stream and the message indeed appeared but on the same time as someone died so it was quickly removed at the same time as "3 hidders left" appeared
this is why i didn't saw it on the moment
Also, maybe you should replace the message by something more understandable ? "unknow" -> "Warning" , "something is coming" -> "Don't stay here" or something similar but not too long i think

I agree with your tutorial idea !


As for the UI bug, im pretty sure you can do something like this, this is just a thing about reseting every flag to their default state

if (player == GameNetworkManager.Instance.localPlayerController)
{
    HUDManager.Instance.gasHelmetAnimator.SetBool("gasEmitting", false);
    player.hasBegunSpectating = false;
    HUDManager.Instance.RemoveSpectateUI();
    HUDManager.Instance.gameOverAnimator.SetTrigger("revive");
    player.hinderedMultiplier = 1f;
    player.isMovementHindered = 0;
    player.sourcesCausingSinking = 0;
    HUDManager.Instance.HideHUD(false);
}

**Comment by ZigzagAwaka** [comment]
When do you think you are going to publish the update? Not to put stress on you or anything of course, just asking

**Comment by gogozooom** [comment]
I have been out of the house this past weekend so I couldn't get very much work done on it. But this week looks nice and free, so I will likely finish the last planned feature by the end of this week!
I will take my time on this though because I would rather have comprehensible information, than a big wall of text as an introduction to the mod.

**Comment by ZigzagAwaka** [comment]
Yeah ok no problem take your time

**Comment by gogozooom** [comment]
Now added/fixed in the v1.4.0 update!

**Comment by ZigzagAwaka** [comment]
Thannks for the hard work ! I will test the controller support and give a feedback very soon,

**Comment by ZigzagAwaka** [comment]
I can confirm you that controller support is working as expected, thanks for the update!
